language: swift
xcode_project: ToastMessage.xcodeproj
xcode_scheme: ToastMessage
xcode_sdk: iphonesimulator9.3
branches:
  only:
    master

script: xcodebuild -project ToastMessage.xcodeproj -scheme ToastMessage -sdk iphonesimulator test