language: swift
xcode_project: ToastMessage.xcodeproj
xcode_scheme: ToastMessageTests
xcode_sdk: iphonesimulator9.0 
branches:
  only:
    master

script: xcodebuild -project ToastMessage.xcodeproj -scheme ToastMessageTests -sdk iphonesimulator test