osx_image: xcode8.3
language: swift
xcode_project: ToastMessage.xcodeproj
xcode_scheme: ToastMessage
xcode_sdk: iphonesimulator9.3
branches:
  only:
    master

before_install:
  - brew unlink swiftlint
  - brew uninstall swiftlint
  - brew install swiftlint
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

before_script:
  - swiftlint

script: 
  - set -o pipefail
  - xcodebuild clean build test -project ToastMessage.xcodeproj -scheme ToastMessage -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1'